#!/bin/bash

if [ ! -f ./antlr-4.7.2-complete.jar ]; then
    #   echo "No ANTLR JAR found, downloading it now..."
      curl -O https://www.antlr.org/download/antlr-4.7.2-complete.jar
fi

export CLASSPATH="./antlr-4.7.2-complete.jar:$CLASSPATH"
java -jar ./antlr-4.7.2-complete.jar Little.g4
javac *.java
java Driver $1

rm -rf *.class
rm -rf Little*.java
rm -rf *.tokens
rm -rf *.interp
